config/routes.rb
Rails.application.routes.draw do
  resources :families
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/family.rb
class Family < ApplicationRecord
  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         belongs_to :family
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  before_action :set_family, only: %i[ show edit update destroy ]

  # GET /families or /families.json
  def index
    @families = Family.all
  end

  # GET /families/1 or /families/1.json
  def show
  end

  # GET /families/new
  def new
    @family = Family.new
  end

  # GET /families/1/edit
  def edit
  end

  # POST /families or /families.json
  def create
    @family = Family.new(family_params)

    respond_to do |format|
      if @family.save
        format.html { redirect_to family_url(@family), notice: "Family was successfully created." }
        format.json { render :show, status: :created, location: @family }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @family.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /families/1 or /families/1.json
  def update
    respond_to do |format|
      if @family.update(family_params)
        format.html { redirect_to family_url(@family), notice: "Family was successfully updated." }
        format.json { render :show, status: :ok, location: @family }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @family.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /families/1 or /families/1.json
  def destroy
    @family.destroy

    respond_to do |format|
      format.html { redirect_to families_url, notice: "Family was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_family
      @family = Family.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def family_params
      params.fetch(:family, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/views/families/_family.html.erb
<div id="<%= dom_id family %>">
</div>

app/views/families/_form.html.erb
<%= form_with(model: family) do |form| %>
  <% if family.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(family.errors.count, "error") %> prohibited this family from being saved:</h2>

      <ul>
        <% family.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/families/edit.html.erb
<h1>Editing family</h1>

<%= render "form", family: @family %>

<br>

<div>
  <%= link_to "Show this family", @family %> |
  <%= link_to "Back to families", families_path %>
</div>

app/views/families/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Families</h1>

<div id="families">
  <% @families.each do |family| %>
    <%= render family %>
    <p>
      <%= link_to "Show this family", family %>
    </p>
  <% end %>
</div>

<%= link_to "New family", new_family_path %>

app/views/families/new.html.erb
<h1>New family</h1>

<%= render "form", family: @family %>

<br>

<div>
  <%= link_to "Back to families", families_path %>
</div>

app/views/families/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @family %>

<div>
  <%= link_to "Edit this family", edit_family_path(@family) %> |
  <%= link_to "Back to families", families_path %>

  <%= button_to "Destroy this family", @family, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FamillyBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>